version: "3.8"

services:
  app:
    image: appnet
    environment:
      MONGO_URL: "mongodb://db:27017/docker_test"
    depends_on:
      - db
    ports:
      - "3000:3000"

  db:
    image: mongo
